// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgnqefivlbnshzbdthnm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nbnFlZml2bGJuc2h6YmR0aG5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNDQzNDgsImV4cCI6MjA2ODgyMDM0OH0.Chx_oJzabPorq5E8sgydIHYWB97qXqEUYGx1W9XHhHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});